### PR TITLE
Getting started

### PR DESCRIPTION
**Pull request by ggcrunchy**
Hi!

Apologies for taking so long to kick this off. There isn't **much** here, but it's a start.

I have an x64 target in a tiny Visual Studio 2013 solution, with Lua itself and the ArrayFire binding as sub-projects, currently just with a CPU version. (I don't how meaningful the Debug / Release distinction is when targeting the pre-built binary.)

This takes the un-extension'd script name as a command line input. I added the "scripts" directory to Lua's require() path and launch with that in a protected call, using the require() machinery. Not really sure how to target other platforms.

This really only affects the Visual Studio version, I think: I got scared off looking at the porting-to-32 bit instructions for ArrayFire, so I am hoping to make the exe (possibly as an **#ifdef**) launchable as a process, thus all the commented-out stuff in **utils.cpp**. (If anyone has relevant code on this front, it would be greatly appreciated.)

This is Lua 5.1... apart from a little LuaJIT I'm not really familiar with any more recent ABIs, so anybody willing to help port just that stuff would be doing a service!

I'm converting enums to strings (so far just the errors and types), and that seems about right. I'm of two minds right now on which API to bind. I've used the C API thus far, but C++ names on the array methods. I think C++ might be feasible, though I say that without the advantage of deep familiarity. 

Overloading and certain operators (particularly the mutate variants) would require a naming convention, in that case. There is an OO convention in Lua, so it would be fairly natural.

I guess a consistent return policy would be good too, since pointers aren't really a thing but multiple returns are. I've been returning the error code second, but overall maybe it makes sense to come first.

I've been boxing the array, though in C++ it could be placement new()'d.

Also, I'm using just stock Lua, but there are a bunch of [binding libraries](http://lua-users.org/wiki/BindingCodeToLua) out there, too, though I've not tried any of them myself.

Anyhow, I've not dared to actually try any of the ArrayFire calls just yet. :smile: Was just puttering around for now trying to tease out some patterns.

This has been fairly cobbled together so far. Let me know if you have any opinions or suggestions.

### CODE REVIEW

**Comment by pavanky** [comment]
@ggcrunchy Thanks for taking time to do this!

One minor issue though. Can you edit the commit message for the second commit ? Everything after the semi colon should be in a new line with a blank line after the first.

**Comment by ggcrunchy** [comment]
Done (I think).

**Comment by pavanky** [comment]
@ggcrunchy :+1: 

it looks like the PR is still a work in progress. Let me know when would be a good time to merge.

Also I'd suggest continuing to use C API calls for the bindings. C/C++ may not matter much on Linux, but on Windows it will cause issues when certain parts are compiled with mingw and others with visual studio.

**Comment by ggcrunchy** [comment]
Okay, that sounds good. I'll adjust some of my convenience measures and provide some helpers to write OO wrappers in Lua itself. I'm thinking this will streamline support for LuaJIT, too.

I think I'll give this a couple more weeks, then, to let some structure settle in. I've got a couple situations ready and waiting, as mentioned on the discussion thread, so I'll probably focus on what I need for one of them, QR being the more likely choice. Perhaps I'll try to port two or three of the ArrayFire examples, as well.

**Comment by pavanky** [comment]
@ggcrunchy If you can add a README for the library, I will try to get it to build on a linux machine and see how it goes. I need a bit to understand the structure of the library. right now.

**Comment by ggcrunchy** [comment]
@pavanky Sure, I'll try to put something rough together either tonight or tomorrow night. I want to begin running my stuff through some tests to make sure it works at all, of course! I think I've got most of the API now, aside from the newest index functions and the backend interface functions.

I threw in LuaJIT as well, because it looked like organizing all the functions for stock Lua pretty much dovetailed with putting together an FFI binding. I'd not done this before, so I'd be surprised if there aren't some kinks still.

Is there an idiomatic example available using the C API? I'd like to know I have the right idea about how to deal with ref counts. Also, is there a "**gfor()** in C" example, by any chance? The pattern might lend itself to a Lua iterator.

**Comment by pavanky** [comment]
@ggcrunchy I'd rather not worry about gfor right now. It's spread across multiple functions / features to be honest. I can try to contribute something along those lines once I understand the code base :)

If you have any specific questions about the reference counts, ping me on gitter!

**Comment by pavanky** [comment]
Created a room for lua: https://gitter.im/arrayfire/arrayfire-lua

**Comment by pavanky** [comment]
@ggcrunchy This was conflicting with the changes I had made so I cherry picked your last commit into the master branch. Thanks for taking the initiative to do all of the work!

I think it is better if you forked from arrayfire cleanly at this point.

**Pull request closed without merging**
